'use strict';

module.exports = {
  user: {
    id: { type: 'string', description: 'id 唯一键' },
    username: { type: 'string', description: '用户名' },
    nickName: { type: 'string', description: '昵称' },
    email: { type: 'string', description: '邮箱' },
    mobile: { type: 'string', description: '电话' },
    status: { type: 'integer', description: '状态' },
    avatar: { type: 'string', description: '头像' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
    roles: {
      type: 'array',
      itemType: 'role',
    },
  },
  userList: {
    rows: { type: 'array', itemType: 'user', description: '列表' },
    count: { type: 'integer', description: '记录总数' },
    page: { type: 'integer', description: '当前页' },
    totalPages: { type: 'integer', description: '总页数' },
  },
  role: {
    id: { type: 'string', description: '角色唯一键' },
    name: { type: 'string', description: '角色名' },
    status: { type: 'integer', description: '状态' },
    level: { type: 'integer', description: '角色等级' },
    parentId: { type: 'string', description: '父级ID' },
  },
  rolePage: {
    id: { type: 'string', description: '角色唯一键' },
    name: { type: 'string', description: '角色名' },
    status: { type: 'integer', description: '状态' },
    level: { type: 'integer', description: '角色等级' },
    parentId: { type: 'string', description: '父级ID' },
    description: { type: 'string', description: '描述' },
    enabled: { type: 'boolean', description: '启用状态' },
    sort: { type: 'integer', description: '排序' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
    menus: {
      type: 'array', description: '角色菜单',
      itemType: 'menu',
    },
  },
  roleList: {
    rows: { type: 'array', itemType: 'rolePage', description: '角色列表' },
    count: { type: 'integer', description: '记录总数' },
    page: { type: 'integer', description: '当前页' },
    totalPages: { type: 'integer', description: '总页数' },
  },
  menu: {
    title: { type: 'string', description: '菜单名称' },
    parentId: { type: 'string', description: '父级菜单id' },
    icon: { type: 'string', description: '图标' },
    menuType: { type: 'integer', description: '菜单类型' },
    sort: { type: 'integer', description: '排序' },
    path: { type: 'string', description: '地址' },
    operateType: { type: 'string', description: '操作类型' },
    hidden: { type: 'boolean', description: '菜单是否隐藏' },
    permission: { type: 'string', description: '权限标识' },
    name: { type: 'string', description: '组件名' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
  },
  menuTree: {
    title: { type: 'string', description: '菜单名称' },
    parentId: { type: 'string', description: '父级菜单id' },
    icon: { type: 'string', description: '图标' },
    menuType: { type: 'integer', description: '菜单类型' },
    sort: { type: 'integer', description: '排序' },
    path: { type: 'string', description: '地址' },
    operateType: { type: 'string', description: '操作类型' },
    hidden: { type: 'boolean', description: '菜单是否隐藏' },
    permission: { type: 'string', description: '权限标识' },
    name: { type: 'string', description: '组件名' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
    children: {
      type: 'array', description: '二级子菜单',
      itemType: 'menu',
    },
  },
  login: {
    token: { type: 'string', description: 'token' },
  },
  captcha: {
    img: { type: 'string', description: 'img' },
    captchaKey: { type: 'string', description: 'captchaKey' },
  },
  assApp: {
    accessKeyId: { type: 'string', description: 'accessKeyId' },
    secret: { type: 'string', description: '秘钥' },
    descContent: { type: 'string', description: '描述' },
    keyType: { type: 'string', description: '类型' },
    enabled: { type: 'boolean', description: '启用状态' },
    used: { type: 'boolean', description: '使用状态' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
  },

  sysConfig: {
    id: { type: 'string', description: '唯一键' },
    name: { type: 'string', description: '配置字段名' },
    value: { type: 'string', description: '配置值' },
    remark: { type: 'string', description: '配置说明' },
    createdAt: { type: 'string', description: '创建时间' },
    updatedAt: { type: 'string', description: '更新时间' },
  },
};
